services:
  web:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - my-notes-mongo
  my-notes-mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
